### ISSUE TITLE
All of UnityAdsSettings are reset when press "Stop" on UnityEditor

### ISSUE THREAD

**Issue by yasuyuki-kamata** [Applifier/unity-ads-helper#1]
All of settings are reset when press "Stop" on Editor.

Environment:
 UnityEditor : 5.1.2 f1
 UnityAds A$ package : 1.2.1
 Unity Ads Helper : latest (9d057634b2c4e9943dec6eb1b6069d3858c6ef83)

Step to reproduce:
1. make simple project for showing UnityAds using Unity Ads Helper
2. change UnityAdsSettings scriptable object
3. press "Play" button
4. press "Stop" button
5. check the setting file

**Comment by wcoastsands** [comment]
This should be fixed now (186055e). Changes to UnityAdsSettings are now actively saved.
